### ISSUE TITLE
I can fix your iOS issues, but running into issues with Android I might need help with

### ISSUE THREAD

**Issue by conrad-vanl** [mfrachet/rn-native-portals#10]
@mfrachet I've been able to update your swift code to get it fully working on the iOS side, and I can open up a PR on your library to wire up the linking correctly. However, it seems your android implementation might be problematic, and I'm not familiar enough with Android to fix. I'd be happy to open up a PR that gets iOS up to snuff, but I want to see first if you'd be willing to provide some guidance on the android front?

I'm seeing two issues on Android:

1. In conjunction with react-native-video, it appears that video remounts / restarts when reparenting
2. I believe if the underlying component re-renders after portaling, I get an error similar to this:

![Screen Shot 2020-10-29 at 10 10 57 PM](https://user-images.githubusercontent.com/103927/97655664-a04d3200-1a33-11eb-8328-fe3b5f8eecdb.png)

This is on react-native 62. I have iOS working flawlessly though!

**Comment by mfrachet** [comment]
Hello there :)

I don't have future plans for this project and I won't put effort on this. Feel totally free to do whatever you want on a fork or even on a new similar project.

Thanks for the message and happy you managed to make this work for iOs 👍 😊 !

**Comment by louiszawadzki** [comment]
Hi @conrad-vanl, I faced the same issue as you.

We realised that when we unmounted the Destination while it was "containing" the Origin, we had this error.
So we decided to hide the Destination (by setting `overflow: hidden` and `height: 0px`) instead of unmounting it.

It does seem that your issue is a bit different, but I thought it might help you :)
